README.md
Avoid looking at the script. Github didn't refresh the base state. Just look at the readme please.
=> chore: adds readme

solidity/contracts/OracleAggregator.sol, test/unit/oracle-aggregator.spec.ts
We realized that there was a corner case where:
- An oracle had been forced for a pair
- The oracle had lost support for the pair
- Only an admin could change the assigned oracle
So what we are doing now, is that we are allowing anyone to change a forced oracle, if said oracle has lot support
=> feat: allow modify when pair lost support

solidity/contracts/TransformerOracle.sol, solidity/contracts/test/TransformerOracle.sol, solidity/interfaces/ITransformerOracle.sol, test/unit/transformer-oracle.spec.ts
We are now implementing `shouldMapToUnderlying` and `avoidMappingToUnderlying`. They don't do anything yet, but they allow configuring
They will have an effect in the next PR
=> feat: add avoid mapping to underlying

solidity/contracts/TransformerOracle.sol, solidity/contracts/test/TransformerOracle.sol, solidity/interfaces/ITransformerOracle.sol, test/unit/transformer-oracle.spec.ts
We are now adding Access Control to the transformer oracle
=> feat: transformer oracle add access control

solidity/contracts/TransformerOracle.sol, solidity/contracts/test/TransformerOracle.sol, solidity/interfaces/ITransformerOracle.sol, test/unit/transformer-oracle.spec.ts
We are now implementing `quote` for the transformer oracle
=> feat: transformer oracle add quote

slither.config.json, solidity/contracts/adapters/UniswapV3Adapter.sol, solidity/contracts/test/UniswapV3Pool.sol, solidity/contracts/test/adapters/UniswapV3Adapter.sol, solidity/interfaces/adapters/IUniswapV3Adapter.sol, test/integration/uniswap-v3-add-support-gas.spec.ts, test/unit/adapters/uniswap-v3-adapter.spec.ts
So this is the big change. Now, instead of trying to prepare all pools (and maybe revert trying), we will try to prepare pools and stop before failing
=> fix: dont fail with too much gas

solidity/contracts/adapters/UniswapV3Adapter.sol, solidity/interfaces/adapters/IUniswapV3Adapter.sol, test/unit/adapters/uniswap-v3-adapter.spec.ts
We are now reverting when the gas is so low that we can't prepare any pools at all
=> feat: fail when gas too low

deploy/001_stateful_chainlink_adapter.ts, deploy/003_oracle_aggregator.ts
We update deployment salts according to the new versions.
=> fix: updated deployment salts

hardhat.config.ts, solidity/contracts/StatefulChainlinkOracle.sol, solidity/contracts/test/StatefulChainlinkOracle.sol, solidity/contracts/utils/Governable.sol, solidity/interfaces/IStatefulChainlinkOracle.sol, solidity/interfaces/utils/IGovernable.sol, test/unit/stateful-chainlink-oracle.spec.ts, test/utils/behaviours.ts
We are now just copying the Chainlink Oracle (and its unit tests) from dca-v2-core to this repository
=> feat: copy chainlink from core

deploy/001_stateful_chainlink_oracle.ts, deploy/002_uniswap_v3_adapter.ts, deploy/004_oracle_aggregator.ts, hardhat.config.ts, solidity/contracts/StatefulChainlinkOracle.sol, solidity/contracts/test/StatefulChainlinkOracle.sol, solidity/interfaces/IStatefulChainlinkOracle.sol, test/integration/stateful-chainlink-oracle.spec.ts, test/unit/stateful-chainlink-oracle.spec.ts
We are now copying the integration test for the Chainlink oracle from dca-v2-core to this repository
=> test: stateful chainlink oracle integration

hardhat.config.ts, package.json, solidity/contracts/OracleAggregator.sol, solidity/contracts/StatefulChainlinkOracle.sol, solidity/contracts/adapters/UniswapV3Adapter.sol, solidity/contracts/libraries/TokenSorting.sol, solidity/contracts/test/StatefulChainlinkOracle.sol, solidity/interfaces/IStatefulChainlinkOracle.sol, test/unit/adapters/uniswap-v3-adapter.spec.ts, yarn.lock
We are now doing a few things:
- Removed the dependency to mean-finance/dca-v2-core (will allow us to avoid circular dependencies)
- Updating the package version
- Updating the docs to our new format
=> chore: update docs and dependencies

deploy/001_stateful_chainlink_oracle.ts, deploy/002_uniswap_v3_adapter.ts, deploy/003_identity_oracle.ts, deploy/004_oracle_aggregator.ts, hardhat.config.ts, package.json, test/integration/comprehensive-oracle-test.spec.ts, test/integration/stateful-chainlink-oracle.spec.ts, test/integration/uniswap-v3-add-support-gas.spec.ts, test/utils/evm.ts, yarn.lock
We are now importing the Chainlink Registry npm library, and deploying it as part of the tests 🎉
=> chore: import and deploy chainlink registry

deploy/001_stateful_chainlink_oracle.ts, deploy/002_uniswap_v3_adapter.ts, deploy/003_identity_oracle.ts, deploy/004_oracle_aggregator.ts, hardhat.config.ts, package.json, solidity/contracts/StatefulChainlinkOracle.sol, solidity/contracts/test/StatefulChainlinkOracle.sol, solidity/interfaces/IStatefulChainlinkOracle.sol, test/integration/comprehensive-oracle-test.spec.ts, test/integration/stateful-chainlink-oracle.spec.ts, test/integration/uniswap-v3-add-support-gas.spec.ts, test/utils/evm.ts, yarn.lock
Just a minor refactor for some gas savings
=> refactor: avoid mapping of mapping

deploy/001_stateful_chainlink_oracle.ts, solidity/contracts/StatefulChainlinkOracle.sol, solidity/contracts/test/StatefulChainlinkOracle.sol, solidity/interfaces/IStatefulChainlinkOracle.sol, test/unit/stateful-chainlink-oracle.spec.ts
We are now removing all code related to WETH and stablecoins
=> refactor: remove weth and stablecoins

codechecks.yml, deploy/001_stateful_chainlink_oracle.ts, deploy/005_transformer_oracle.ts, hardhat.config.ts, package.json, solidity/contracts/StatefulChainlinkOracle.sol, test/integration/transformer-oracle.spec.ts, yarn.lock
We are now adding a deploy script + integration test for the Transformer Oracle
=> test: add transformer oracle test

solidity/contracts/StatefulChainlinkOracle.sol, solidity/interfaces/IStatefulChainlinkOracle.sol, test/integration/stateful-chainlink-oracle.spec.ts, test/unit/stateful-chainlink-oracle.spec.ts
We are now adding support for forex addresses. So we can quote ERC20 to forex, or forex to forex
=> feat: support forex addresses

solidity/contracts/TransformerOracle.sol
We are now just simplifying `quote` for the Transformer Oracle. Instead of having multiple `if/else` statements, we simply transform the input if needed, and then transform the output if needed
=> refactor: simplify quote in transformer oracle

solidity/contracts/adapters/UniswapV3Adapter.sol, solidity/interfaces/adapters/IUniswapV3Adapter.sol, test/unit/adapters/uniswap-v3-adapter.spec.ts
We are now making `_FIXED_GAS_COST_TO_SUPPORT_POOL` mutable, so that it something changes related to gas costs, we can react to it
=> feat: add mutable gas cost for pool support

solidity/contracts/StatefulChainlinkOracle.sol, yarn.lock
We are making a few small changes that would allow us to improve precision when performing quotes
=> refactor: improve precision in quotes

deploy/005_transformer_oracle.ts, solidity/contracts/TransformerOracle.sol, solidity/contracts/test/TransformerOracle.sol, test/integration/transformer-oracle.spec.ts, test/utils/defillama.ts
We are now making `quote` recursive. We also have a nice integration test that makes sure everything works as expected
=> refactor: make quote recursive
