solidity/contracts/OracleAggregator.sol
solidity/contracts/adapters/StatefulChainlinkOracleAdapter.sol
solidity/contracts/adapters/UniswapV3Adapter.sol
solidity/interfaces/ITokenPriceOracle.sol
test/e2e/oracle-aggregator.spec.ts
test/integration/comprehensive-oracle-test.spec.ts
test/unit/adapters/stateful-chainlink-oracle-adapter.spec.ts
test/unit/adapters/uniswap-v3-adapter.spec.ts
test/unit/oracle-aggregator.spec.ts

We've realized that we could simplify our oracles by removing the versions of `quote`, `addOrModifySupportForPair` and `addSupportForPairIfNeeded` that didn't take any custom data.
We are doing this because:
- Oracles will now be simpler to build, test and maintain
- In the cases where oracles needed data, having a function that didn't take any was weird. Should that function fail?
Now, if a oracle doesn't need any custom data, it can just ignore the parameter

refactor: remove functions without data

---

solidity/contracts/adapters/UniswapV3Adapter.sol
solidity/contracts/test/adapters/UniswapV3Adapter.sol
test/unit/adapters/uniswap-v3-adapter.spec.ts

We are now implementing `SimpleOracle` in the `UniswapV3Adapter`. This change allows us to delete both `addOrModifySupportForPair` and `addSupportForPairIfNeeded`, and their tests. We now just need to implement and test `_addOrModifySupportForPair`
This will make our lives easier moving forward, and everything will be easier to test

refactor: implement simple oracle in uni adapter

---

solidity/contracts/OracleAggregator.sol
solidity/contracts/test/OracleAggregator.sol
test/unit/oracle-aggregator.spec.ts
test/utils/behaviours.ts

We are now implementing `SimpleOracle` in the oracle aggregator. This change allows us to delete `addSupportForPairIfNeeded`, and all its tests

refactor: implement simple oracle in aggregator

---

package.json
slither.config.json
solidity/contracts/TransformerOracle.sol
solidity/interfaces/ITransformerOracle.sol
test/unit/transformer-oracle.spec.ts
yarn.lock

We are now adding the transformer oracle contract. Per its description:
> This oracle takes the transformer registry, and will transform some dependent tokens into their underlying tokens before quoting. We do this because it's hard to quote `yield-bearing(USDC) => yield-bearing(ETH)`. But we can easily do something like `yield-bearing(USDC) => USDC => ETH => yield-bearing(ETH)`. So the idea is to use the transformer registry to transform between dependent and their underlying, and then quote the underlyings.

feat: add transformer oracle

---

slither.config.json
solidity/contracts/TransformerOracle.sol
solidity/contracts/test/TransformerOracle.sol
solidity/interfaces/ITransformerOracle.sol
test/unit/transformer-oracle.spec.ts

Now, before calling the registry to get the tokens' transformers,  we are checking the config to see if we should map the pair or not. If not, then we act as if there were no transformers at all.
We also renamed `mapPairToUnderlying` to `getMappingForPair`, since it makes more sense now

refactor: check config before calling registry

---

solidity/contracts/TransformerOracle.sol
solidity/contracts/test/TransformerOracle.sol
solidity/interfaces/ITransformerOracle.sol
test/unit/transformer-oracle.spec.ts

We are now implementing `canSupportPair`, `isPairAlreadySupported`, `addOrModifySupportForPair` and `addSupportForPairIfNeeded`

feat: add easy redirect calls

---

solidity/contracts/adapters/UniswapV3Adapter.sol
solidity/contracts/test/adapters/UniswapV3Adapter.sol
test/unit/adapters/uniswap-v3-adapter.spec.ts

We are now adding `_getAllPoolsSortedByLiquidity` to the Uniswap v3 adapter. This function will take a pair, get all existing pools and sort them by liquidity, desc, and return them.
This is the first step of our plan towards avoiding the run out of gas issue

feat: add sort by liquidity

---

solidity/contracts/OracleAggregator.sol
solidity/contracts/TransformerOracle.sol
solidity/contracts/adapters/UniswapV3Adapter.sol
test/unit/adapters/uniswap-v3-adapter.spec.ts
test/unit/oracle-aggregator.spec.ts
test/unit/transformer-oracle.spec.ts

We are now setting the super admin role as its own admin, so we can transfer it in the future

refactor: set super admin role as own admin

---

solidity/contracts/StatefulChainlinkOracle.sol
solidity/contracts/test/StatefulChainlinkOracle.sol
solidity/interfaces/IStatefulChainlinkOracle.sol
test/unit/stateful-chainlink-oracle.spec.ts

We are now refactoring the Chainlink Oracle so that it implements the new `ITokenPriceOracle` interface

refactor: move chainlink oracle to new interface

---

solidity/contracts/StatefulChainlinkOracle.sol
solidity/interfaces/IStatefulChainlinkOracle.sol
test/unit/stateful-chainlink-oracle.spec.ts

We are now adding `removeUSDStablecoins`, because as @nchamo put it, it should have been there all along 😅

feat: remove usd stablecoins

---

solidity/contracts/StatefulChainlinkOracle.sol
solidity/contracts/test/StatefulChainlinkOracle.sol
solidity/interfaces/IStatefulChainlinkOracle.sol
test/unit/stateful-chainlink-oracle.spec.ts

We are now making the oracle simpler by implementing `SimpleOracle` and removing some extra logic

refactor: implement simple oracle

---

solidity/contracts/StatefulChainlinkOracle.sol
solidity/contracts/test/StatefulChainlinkOracle.sol
solidity/interfaces/IStatefulChainlinkOracle.sol
test/unit/stateful-chainlink-oracle.spec.ts

Thanks to @0xged , we realized that we had a corner case where the oracle wouldn't work as expected. This scenario could happen if we removed a mapping (to USD or another token) and suddenly a pair lost support. 
In that case, the pricing plan was already set, and we couldn't remove it by reconfiguring the pair (because it reverted). With this change, we can now lose support

fix: add ability to lose support

---

solidity/contracts/StatefulChainlinkOracle.sol
solidity/contracts/test/StatefulChainlinkOracle.sol
test/integration/comprehensive-oracle-test.spec.ts
test/integration/stateful-chainlink-oracle.spec.ts
test/unit/stateful-chainlink-oracle.spec.ts

We are now making a change so that plans are stored for the mapped version of a pair. This has a few benefits:
1. If a register the pair WETH/DAI, then it will associated to ETH/USD
2. This means that WETH/USDT already has a plan calculated
3. If we remove the mapping USDT => USDT, then all pairs X/USDT will stop working, until they are reconfigured
_Note: if two tokens are mapped to the same address, then we will use their original version. This is so that stablecoin to stablecoin pairs used their feeds, and we don't assume that they are 1:1_

refactor: store plan for mapped

---

solidity/contracts/StatefulChainlinkOracle.sol
solidity/interfaces/IStatefulChainlinkOracle.sol
test/integration/stateful-chainlink-oracle.spec.ts
test/unit/stateful-chainlink-oracle.spec.ts

Before this change, we couldn't quote two tokens that mapped to the same address. It would work only if they had their own individual feeds
So the idea here is that if two tokens maps to the same address, then we consider them the same, and we will quote 1:1. We should now be very careful in what we map to other addresses

refactor: support same tokens pair

---

deploy/001_stateful_chainlink_oracle.ts
solidity/contracts/StatefulChainlinkOracle.sol
solidity/contracts/test/StatefulChainlinkOracle.sol
solidity/interfaces/IStatefulChainlinkOracle.sol
test/unit/stateful-chainlink-oracle.spec.ts

Before this change, we were able to configure the max delay allowed for Chainlink feeds. The thing is that for all networks, the max delay was 24hs 😅 
I went over most Chainlink feeds and in fact, the max delay is 24hs. But, at the same time, `maxDelay` was mutable, so we were reading storage once for each read feed. And we could potentially read 4 feeds per pair
So the idea is to simplify everything by just hardcoding the max 24hs delay. In an ideal world (alpha drop), we would use the actual feed heartbeat instead of a max delay that covers all feeds

refactor: make max delay constant

---

solidity/contracts/StatefulChainlinkOracle.sol

Since we are now longer treating usd stablecoins as a special case, we can remove this comment that doesn't make sense anymore

chore: remove unrelated comment

---

solidity/contracts/TransformerOracle.sol
solidity/contracts/test/TransformerOracle.sol
test/unit/transformer-oracle.spec.ts

We are now simplifying `_getTransformers` so that it's easier to read and maintain

refactor: simplify get transformers

---

solidity/contracts/TransformerOracle.sol
solidity/interfaces/ITransformerOracle.sol
test/unit/transformer-oracle.spec.ts

We are now adding the possibility to set pair-specific mappings config. The idea is that we will check if a pair has some specific mapping set. If it doesn't, then we will check the global config

feat: set specific mapping config

---

solidity/contracts/StatefulChainlinkOracle.sol

If a token were to have decimals between `type(int8).max < decimals <= type(uint8).max`, then we would overflow. By using `int16`, we can avoid this problem

fix: use int16 for decimals

---

solidity/contracts/TransformerOracle.sol
solidity/interfaces/ITransformerOracle.sol
test/unit/transformer-oracle.spec.ts

We are now adding the possibility to clear pair-specific mapping config for a pair

feat: clear specific mapping config

---

solidity/contracts/TransformerOracle.sol
solidity/contracts/test/TransformerOracle.sol
test/integration/transformer-oracle.spec.ts
test/unit/transformer-oracle.spec.ts

We are now doing a small refactor to introduce `_getTransformersOptimized`. The idea is simple, if we know before hand if a token doesn't have an underlying, then we can avoid fetching its transformer. This would make the call a little cheaper
So what we did was:
- Introduced `_fetchTransformers` that fetches between 0 and 2 transformers, based on the params
- Moved transformer hiding logic to `_hideTransformersBasedOnConfig`
- Introduced `_getTransformersOptimized`, which basically calls `_fetchTransformers` & `_hideTransformersBasedOnConfig`
This change might not make sense yet, since we are not using it, but it will on a following PR

refactor: get transformers optimized

---

solidity/contracts/TransformerOracle.sol
solidity/contracts/test/TransformerOracle.sol

We are now using `getRecursiveMappingForPair` instead of `getMappingForPair` on:
- `canSupportPair`
- `isPairAlreadySupported`
- `addOrModifySupportForPair`
- `addSupportForPairIfNeeded`
Note: we still need to update `quote`, which will be done in a following PR

refactor: use recursive

---

deploy/006_api3_chainlink_adapter_factory.ts
solidity/contracts/adapters/api3-chainlink-adapter/API3ChainlinkAdapterFactory.sol
test/integration/api3_chainlink_adapter.spec.ts
test/unit/adapters/api3-chainlink-adapter/api3-chainlink-adapter-factory.spec.ts

We are now adding a new factory contract for the API3 adapter. This will allow us to deploy adapters more easily. We are using CREATE2 to deploy the contracts, based on the address of the proxy and the description too
_Note: integration tests will be added in the next PR_

feat: add api3 adapter factory
